name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: setup build flags
        run:
          export PLATFORMIO_BUILD_FLAGS=-DWIFI_SSID="$WIFI_SSID"-DWIFI_PASS="$WIFI_PASS";
          echo $PLATFORMIO_BUILD_FLAGS
        env:
          WIFI_PASS: "${{ vars.TEST_PASS }}" #${{ secrets.WIFI_PASS }}
          WIFI_SSID: "${{ vars.TEST_SSID }}" #${{ secrets.WIFI_SSID }}

      - name: Run PlatformIO
        run: pio run
        env:
          WIFI_PASS: "${{ vars.TEST_PASS }}" #${{ secrets.WIFI_PASS }}
          WIFI_SSID: "${{ vars.TEST_SSID }}" #${{ secrets.WIFI_SSID }}
          PLATFORMIO_BUILD_FLAGS: -DWIFI_SSID='"'$WIFI_SSID'"' -DWIFI_PASS='"'$WIFI_PASS'"'
      - uses: AButler/upload-release-assets@v3.0 
        with:
          files: ".pio/build/release/firmware.bin"
          repo-token: ${{ secrets.GITHUB_TOKEN }}