name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - shell: bash
        env:
          WIFI_PASS: ${{ secrets.WIFI_PASS }}
          WIFI_SSID: ${{ secrets.WIFI_SSID }}
        run: |
          echo $WIFI_PASS; echo $WIFI_PASS
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run PlatformIO
        run: pio run
        env:
          PLATFORMIO_BUILD_FLAGS: -DWIFI_PASS=${{ secrets.WIFI_PASS }} -DWIFI_SSID=${{ secrets.WIFI_SSID }}